name: Benchmark

on: push

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Setup
        run: mix do deps.get, compile

      - name: Benchmark Part 1
        run: mix d02.p1 -b

      - name: Benchmark Part 2
        run: mix d02.p2 -b